# Generated by Django 4.2.6 on 2023-11-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_draw_alter_game_winner_alter_player_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='board',
            field=models.JSONField(),
        ),
    ]
